{% set name = "jupyter_client" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fbab64100a0dcac7701b1e0f1a4412f1ccb45546ff2ad9bc4fcbe4e19804811

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:RunApp.launch_instance

requirements:
  host:
    - pip
    - python
    - hatchling 1.8
    - setuptools
    - wheel
  run:
    - python
    - importlib_metadata >=4.8.3  # [py<310]
    - jupyter_core >=4.12,!=5.0.*
    - python-dateutil >=2.8.2
    - pyzmq >=23.0
    - tornado >=6.2
    - traitlets >=5.3

test:
  source_files:
    - tests
  requires:
    - codecov
    - coverage
    - ipykernel >=6.14
    - mypy
    - paramiko  # [win]
    - pip
    - pre-commit
    - pytest
    - pytest-jupyter-client >=0.4.1
    - pytest-cov
    - pytest-timeout
  imports:
    - jupyter_client

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter protocol implementation and client libraries.
  description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels.
    It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
  dev_url: https://github.com/jupyter/jupyter_client
  doc_url: https://jupyter-client.readthedocs.io

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
    - davidbrochart
