{% set version = "5.2.1" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  fn: jupyter_client-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: 462790d46b244f0a631ea5e3cd5cdbad6874d5d24cc0ff512deb7c16cdf8653d

build:
  number: 0
  script: pip install --no-deps .
  entry_points:
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - traitlets
    - jupyter_core
    - python-dateutil >=2.1
    - pyzmq >=13

test:
  commands:
    - jupyter kernelspec -h
    - jupyter run -h
  imports:
    - jupyter_client

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: Jupyter protocol implementation and client libraries
  description: |
    jupyter client contains the reference implementation of the Jupyter
    protocol.It also provides Python API for starting, managing and
    communicating with Jupyter kernels.
  doc_url: http://jupyter-client.readthedocs.org/
  doc_source_url: https://github.com/jupyter/jupyter_client/blob/master/docs/index.rst
  dev_url: https://github.com/jupyter/jupyter_client

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
