{% set name = "jupyter_client" %}
{% set version = "8.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47ac9f586dbcff4d79387ec264faf0fdeb5f14845fa7345fd7d1e378f8096011

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:RunApp.launch_instance

requirements:
  host:
    - pip
    - python
    - hatchling
    - setuptools
    - wheel
  run:
    - python
    - entrypoints
    - jupyter_core >=4.9.2
    - nest-asyncio >=1.5.4
    - python-dateutil >=2.8.2
    - pyzmq >=23.0
    - tornado >=6.2
    - traitlets

test:
  requires:
    - codecov
    - coverage
    - ipykernel >=6.12
    - ipython
    # Use ipython_genutils to fix tests on osx-arm64
    - ipython_genutils  # [osx-arm64]
    - mypy
    - pip
    - pytest
    - pytest-asyncio >=0.18
    - pytest-cov
    - pytest-timeout
  imports:
    - jupyter_client

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter protocol implementation and client libraries.
  description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels.
    It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
  dev_url: https://github.com/jupyter/jupyter_client
  doc_url: https://jupyter-client.readthedocs.io

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
    - davidbrochart
