{% set version = "4.4.0" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  fn: jupyter_client-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: c99a52fac2e5b7a3b714e9252ebf72cbf97536d556ae2b5082baccc3e5cd52ee

build:
  number: 0
  script: pip install --no-deps .
  entry_points:
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance

requirements:
  build:
    - python
    - pip
  run:
    - python
    - traitlets
    - jupyter_core
    - pyzmq >=13

test:
  commands:
    - jupyter kernelspec -h
  imports:
    - jupyter_client

about:
  home: http://jupyter.org
  license: BSD 3-clause
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
