{% set version = "6.1.2" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: 5724827aedb1948ed6ed15131372bc304a8d3ad9ac67ac19da7c95120d6b17e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - entrypoints
    - jupyter_core >=4.6.0
    - python >=3.5
    - python-dateutil >=2.1
    - pyzmq >=13
    - tornado >=4.1
    - traitlets

test:
  requires:
    - ipykernel
    - ipython
    - pytest
    - pip
  imports:
    - jupyter_client
  commands:
    - pip check
    - jupyter kernelspec list
    - jupyter run -h
    - pytest --pyargs jupyter_client

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter/jupyter_client
  doc_url: https://jupyter-client.readthedocs.io/en/stable/
  doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
