{% set version = "7.1.2" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: 4ea61033726c8e579edb55626d8ee2e6bf0a83158ddf3751b8dd46b2c5cd1e96

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:RunApp.launch_instance

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python >=3.6.1
    - entrypoints
    - jupyter_core >=4.6.0
    - nest-asyncio >=1.5
    - python-dateutil >=2.1
    - pyzmq >=13
    - tornado >=4.1
    - traitlets
    
test:
  requires:
    - python <3.10
    - async_generator
    - codecov
    - coverage
    - ipykernel
    - ipython
    # Use ipython_genutils to fix tests on arm64 
    - ipython_genutils
    - mock
    - pip
    - pytest
    - mypy
    - pytest-asyncio
    - pytest-cov
    - pytest-timeout
  imports:
    - jupyter_client

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter/jupyter_client
  doc_url: https://jupyter-client.readthedocs.io/en/stable/
  doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
    - davidbrochart
