travis:
  secure:
    BINSTAR_TOKEN: nZv97a9fLFFFGQFcNddm6dQM6Yz3tjY3etu1LqH1vO85vR9d9Q4Rfo3a8CKvRtd6UgrIZC/hy6ZtPn2C+6D6ecK+xAfwuUAi0TqUUvYdsR94xRevsGPXTBbCzIjd2AkhylnDQOB7i5mbtgDcKWIXv1NWc4mb+bt/ksKGMyn1rEscc1XpAEhnBpBqXMeahrvpb40LxlqnyoyrY/R4oNzu3WOhvtHJ3DW3yqKdR2XUOM24I2HlgcbQ/p0fdgQRgnaHCi/nR1Ew9KWEODePwmQhT6qb+VNZjz20pmoWtTMTL5Oqh7+2/InikfQW1hNqUZ4VhNFxOxmi3PY8qXMp7EfWWmTDq54yrX/Qw1F8qI7EleCX0vvro8dBxfe6al24rB3sHk7PbVQq296G6clLnLT09W5F0Tz+7khh60fHgg58etbiLyqgCpXqo5JB9wE0jzb29EsGs4nJwir0O8n8wmSPHN52EDW9deAwxsH1lz/naoFGJhNI9DA8EaEOILJNWEi2y2eWhH52cb6Mm3P+rNM9/pt6tq2ACs3xAlFzy6/2rnxPpTUX5fqMv3Uz9bRaqKHoj7HHsU237rhVLVfcv8fLhBiMi3+fsAMetJuwNdev/QgLZuAfFjGRdXLwlFtcJkOxzTSxlssbB1AOr5C7FfeJdnx0WSX6lpMVhi0raFMgbk0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
