travis:
  secure:
    BINSTAR_TOKEN: GIZgQrkby9wszvPKMRJLnD1Rw3FQRRGpQI8rcTLE24Uq16Uq9qENMv58+uMgdIau+yw5dyK2t4UbYamGANLzzNq0xeA7Puqwcp0j62Ks8j3UJONxq6Js8RwM2ofQhfk2ZJyQ8houSULMNKv8WMur5evnOOXr0qW9mSUN/QgvqRoyL3+eNc2qQ124WBr2lN63rK/LVE/jg+FYT8p2zYTAOzgep3NlMViqg1Ts+oPRgWfkcqtvy0NPAqFCboTzBZEQdmqW1avL7X0fmnuhYwzNCjo6q8WohZqD0QiR8eY4O9KAO1/4/aY1sWpRorBlbma5ifF0jLtKuAqZlTG6Mu60KW/hu9FU9uCbXAMU6U0dHjJPRQdSnL8LQWXYew0qqSBcaTRcZKYL7ukqoD1cINu3c2qsF/9+Hyx4M5gLTiV3fFKUE/uvSJm2sZ8/ks7F3HMkSzj8ZUDh3yGfPsyfsACerzREuDTmpL6ZbNLRpmFZFezZpQffxMDM0y18iTV72IN6Ql/wryfkEUh/7M73t5cidC2o3srTdqy9W1v8yeFo+CIb/hNe4Pxsm/QrcW+Pu6WyCwkVxMDkVJubizOSqDtywFXMAPwgktlmYulAWRusQcdK8ycWoJYLaNa7JW+Gu6xBsBVu9pSytezEEA3SUmAvsH4i03tdkht8uU2rYgG70Xs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
